### ISSUE TITLE
Understand, document and implement a better "fuel" counter for the symbolic engine

### ISSUE THREAD

**Issue by VictorCMiraldo** [tweag/pirouette#90]
At the time of writing, our steps or fuel [counter](https://github.com/tweag/pirouette/blob/04140ac2a8545bcfbcb4213e72ccc685997c1f6e/src/Language/Pirouette/Example/MinSwap.hs#L10) lacks some more intuitive semantics. What does it mean to "not find a counter-example" within 100 steps? Is 100 a lot? Is it very little? 

I propose we follow through with an idea proposed by @serras a while ago and introduce a measure, `sizeOf` over datatypes instead. Now, the `100` could mean that we evaluated (in call-by-need) the `assume res inputs :==>: prove res inputs` where `res = validator inputs` for all `inputs` and `res` such that: `sizeOf res + sizeOf inputs <= 100`

Problems that need some thought: 
  - PLC is a strict language but we can't drive the symbolic engine in a call-by-value fashion, it would constantly keep opening up the first value of an infinite datatype it finds.
  - Is call-by-need really going to ensure we "uniformly" expand the inputs? For example, if the input is of type `(a, b)`, ideally we want to do as many steps exploring the second component as we do steps exploring the first. There's no use in expanding `a` to 99 constructor and `b` to zero

**Comment by aspiwack** [comment]
I don't fully understand the details here. But it could be worth using a notion of height rather than an notion of size (so that `height (x, y) = 1+ max (height a) (height b)`).

This would ensure fairness. But it makes it less clear what to do with types of infinite width (such as `Integer -> a`). And I don't know whether it's applicable to your use-cases.

**Comment by VictorCMiraldo** [comment]
I like that idea! If the types of infinite width are also SMT builtins we might be able to get away with it: the SMT will reason with symbolic integers... :thinking:

**Comment by serras** [comment]
Another idea: keep track of different statistics during execution (# of known constructors, # of metavars, # of beta-reductions...), and give the user back the control. In the future we could say then "run this until you have 50 constructors, and 20 metavars", and so on.

> I don't fully understand the details here. But it could be worth using a notion of height rather than an notion of size (so that `height (x, y) = 1+ max (height a) (height b)`).

I think this might be difficult to implement at first glance, because whereas to keep track of the "size" one only need to increment by 1 each time a constructor is added, this requires knowing _where_ the constructor is added. Fairness is important, though, I would suggest to use a breadth-first instead of a depth-first search to guarantee that property.

**Comment by VictorCMiraldo** [comment]
I think that at this point #92 kind of addresses this; I'll close it for now. If any of the involved parties feel like reopening and bringing up future work, please do so! :)
